name: Generate API Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "maimai_py/**"
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Generate Static Files
        run: mkdir api-docs && pip install httpx pdoc beautifulsoup4 cryptography maimai-ffi && pdoc maimai_py --docformat google -o ./api-docs

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "api-docs/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}/maimai-api.turou.fun
